### ISSUE TITLE
Find diaries by author ID

### ISSUE THREAD

**Issue by benel** [Hypertopic/Cassandre#102]
I have read access to a lot of diaries, related or not to ongoing courses.
On review and marking session, I have to open the diary corresponding to a given student (and his/her team mates).
For now, the only way to do this is opening every diary in a different tab, and then, in each tab, to open the first memo, and check its authors.
It would be more efficient if we had ways to search for a user ID (or sort, at least) in the diaries page.

**Comment by christophe-lejeune** [comment]
A  currently developed feature could help you in this task. It is not documented (yet) because it is uncompleted and will be included in a (planned) deeper refactoring. 

However, the already functioning part of this feature allows you to access a summary of the activity of a dedicated user though the path `/user/<id>` 

Of course, this page follows right management, which means that, by default, only the user has the right to access her/his own activity. 

In order to grant yourself access to some user’s (ie your students) activity, you can add a `readers` field to the user document (same syntax as for memos). 

NB: In the future, users will be able to manage this kind of access her/themselves; you won't have to do it yourself. 

I personally include myself in this (`readers`) field when I create all my students (user) documents, once for all, at the beginning of the academic year (before the users connect to the platform for the first time). 

NB: An inelegant way to circumvent this would be to access the user paths as a server admin. 

I personally also rest on this feature to share my activity to my teaching assistants. Reading my feedbacks to other students helps them to guide their students.

I am aware that the above feature does not match exactly what you asked for… it however helps me in the tasks you described. I hope it could help you… at least partially. Do not hesitate to request improvement to modify these user pages... or to maintain the proposal for an additional feature ;-)

**Comment by christophe-lejeune** [comment]
From f8d14fe4d8da60e4223e0173fbe3343489a8d81c , you can customize sponsors differently for users connecting thanks to a external LDAP or registering as new users. The sponsor will be added as a reader of the user activity, easing the access described here-above.

**Comment by benel** [comment]
> However, the already functioning part of this feature allows you to access a summary of the activity of a dedicated user though the path `/user/<id>`

OK. As you said, it is rather different from what I imagined but it does the job. Thank you very much :)
