### ISSUE TITLE
A memo should be made public again

### ISSUE THREAD

**Issue by benel** [Hypertopic/Cassandre#110]
It seems that, once readers have been assigned to a memo, removing those readers is not sufficient to get the document public again.

Tested on Cassandre 3.21.01.18.

Workaround : erase the field `readers:[]` in CouchDB document.

**Comment by benel** [comment]
The same problem exists with `writers:[]`.

To sum up:
- when it says "Lisible par tous", it isn't world readable,
- when it says "Modifiable par tous", it isn't world writable.

**Comment by benel** [comment]
> when it says "Modifiable par tous", it isn't world writable.

Well, in fact, it doesn't "stick". I changed in it CouchDB but it went back to the original settings. It might be intended.
However the first problem is still there.

**Comment by christophe-lejeune** [comment]
This issue concerns different features, namely: 
* When the `readers` or the `contributors` field is missing, it is inserted when the memo is edited. This (intended) behavior was introduced in order for legacy memo to comply with user management and security issues. 
* When a user clears out `readers` list, she is automatically inserted as one of the readers. This behavior prevents memos from becoming public (this frequently occurs accidentally in the past). This behavior is thus intended and protective. As a consequence, only database admins can henceforth produce publicly readable memos (as you indicated).
* When the `contributors` list is cleared out, the memo should become publicly readable and writable. As you report, this is not the case. I am aware of this issue, but it has not been fixed because there is something strange to give public write access to a memo with restricted read access. Here, again, the current behavior secures user data.  
* When a memo is world readable/writable, it should be listed on the diary page, for registered **and** unregistered users. As you report hereabove, this is not always the case. In fact, it works for publicly readable memos. It does not work for world writable memos. This issue was not fixed up to now, given (a) diary listing is tricky and expensive to maintain (due to multiple and public access rights), (b) public access cases slow down the loading of every diary (a lot of resources are required even when no public memo is involved) and (c) nobody uses the public access (namely for feedback, as this feature was originally designed). 

For all these reasons, I am considering discontinuing public accesses. If you have some arguments for keeping it, do not hesitate to argue to maintain it.

**Comment by benel** [comment]
What would you suggest for my samples?
Updating them each year with the whole list of my students?

**Comment by christophe-lejeune** [comment]
You have the choice between (at least) two strategies. 

* Use the current possibility to remove the last reader with your admin role on the database. The dedicated page will become public and will be listed in its diary. I recommend this behavior for (non sensitive) information that can be shared with the world. This is what is have done here: https://www.cassandre.uliege.be/memo/meto0826_2017_00/

* Give access only to your students (with a dedicated list, renewed each year). I recommend this strategy for information that should not spread outside the class. 
Here is an example (your password will be required): 
https://www.cassandre.uliege.be/memo/a/9ec77de31121303e809d8445f8ff9573

**Comment by benel** [comment]
Preventing people from publishing a memo is a legitimate design decision. However this would require additional coding and refactoring. **For now, users can still do the publishing action but it leads to a broken state** in which: 

- the display (just after the action) says the memo is public, 
- the diary is publicly visible, but its content is not readable,
- the display is different for anonymous and connected people but is unusable for both,
- there is no way (in the UI) to get back to the previous state.

I understand that you don't want to spend time on this bug fix, but if I create the fix, would you be OK to merge it?
