### ISSUE TITLE
When multiple fragments are grounded, they should be removable

### ISSUE THREAD

**Issue by benel** [Hypertopic/Cassandre#113]
```yaml
type: special case
difficulty: low
```

<img width="725" alt="Capture d’écran 2021-10-21 à 09 57 47" src="https://user-images.githubusercontent.com/597307/138235722-d2b33635-7469-4f1c-8f18-d3290b51f47c.png">

I added "creuser" by mistake and I cannot remove it.

#### Workaround
1. Add an extra document as ground.
2. Remove the grounded fragment.
3. Remove the extra document.

**Comment by christophe-lejeune** [comment]
Originally this behavior was intended. Indeed, if groundings can be removed when the coding memo is grounded on/in one memo, we risk to create orphaned memo (memo with no grounding). I however agree that this is restrictive (for the reasons exposed above). The code will thus be modified so that (a) a fragment can be removed even if the memo has only one grounding and that, (b) in that case, the main grounding can not be removed (in order to avoid orphan memo).

**Comment by benel** [comment]
> I added "creuser" by mistake and I cannot remove it.

Now, I can 🎉 Thank you!

**Comment by christophe-lejeune** [comment]
Since ffb5f3199815506f18bbe30ca48aeb7f0a9d5c0d multiples codes of the same fragment are removable
