### ISSUE TITLE
Coding a fragment for the first time should be coherent with successive coding

### ISSUE THREAD

**Issue by benel** [Hypertopic/Cassandre#116]
```yaml
type: special case
difficulty: medium
```

### Reproduction scenario

1. Coding `étudiées à fond avec ardeur et patience` with the new code `étudier`.
2. The result is: 
<img width="711" alt="Capture d’écran 2021-11-08 à 15 20 44" src="https://user-images.githubusercontent.com/597307/140758940-65b8f97a-3ce1-4a8a-bf8e-21329886d844.png">
The grounding should indicate the fragment instead of the paragraph.

3. Coding  `Nous ne pouvons rien connaître` with the existing code `étudier`.
4. The result is:
<img width="711" alt="Capture d’écran 2021-11-08 à 15 21 18" src="https://user-images.githubusercontent.com/597307/140758948-900ccc5e-c683-4b7e-96de-26e5e4c32c89.png">
The groundings should indicate also the fragment created on step 1.

5. Coding `je vous ai étudiées à fond avec ardeur et patience` with the existing code `étudier`.
6. The result is 
<img width="807" alt="Capture d’écran 2021-11-08 à 15 22 20" src="https://user-images.githubusercontent.com/597307/140758954-c25a6a6a-be77-45b1-9f3b-393c7377a756.png">
The new groundings are coherent with steps 4 and 5.

**Comment by christophe-lejeune** [comment]
In my first attempts, I fail to reproduce this behavior : the first coding produced the same kind of preview in the grounding panel that the second and third coding (step 3 and 4). 

The reason ? My tests were made with an interview and, in such a scenario, the first (interviewer's) question is never coded (because, in such a case, the material consists of the informant's answers).

I succeed by coding the first paragraph of the material. Indeed, under such circumstances, the here-above reported problem occurs. This happens because the current line (in the source code) prevents to code a fragment originating from the first paragraph:

https://github.com/Hypertopic/Cassandre/blob/coding/app/lib/shared.js#L294

I assume this code is a consequence from previous MarkDown convention, where paragraph referencing was different (the first paragraph was the name/title of the memo). 

At first glance, showing the beginning of the memo seemed not misleading in this case. But, as you showed, it becomes a problem when additional fragments are codes. The `if` condition will thus be modified so that coding behaves the same, whatever paragraph is the first-one coded.

**Comment by benel** [comment]
Thank you for the fixes!
