### ISSUE TITLE
The text fragment should stay selected while a code is created

### ISSUE THREAD

**Issue by benel** [Hypertopic/Cassandre#120]
It is **already** possible to "code" a fragment with Cassandre by:
1. selecting a fragment of the current memo,
2. Typing the name of the "code", 
3. Pushing the "label" icon button (or hitting enter).

**But** the default behaviour of the browser causes the text highlight to disappear when focusing on a text box.
I misinterpreted this lack of visual cue, and thought the only way to go was doing the step in the following order : 2 1 3.
I wrote a short user manual for this. 120 students did this for *all* their codings, got very frustrated, and told it in the course feedback... 

Now I know I was wrong, and will tell it to the students.
However should it be possible to a have a visual cue so they can find the way to do this even if they are not listening to my instructions (some do:wink:)?

**Comment by christophe-lejeune** [comment]
Thank you very much for this proposal. 

I was not aware that you gave 2 1 3 instructions to your students. Indeed, this sequence seems (a bit) counterintuitive and I can understand your (and their) frustration. I am astonished that, being annoyed by this behavior, our students did not try other ways to code, and did not "discover" on their own that the 1 2 3 sequence is possible. My students are very prone to discovering undocumented features ;-) 

By the way, yes, of course, I am aware of this "lack of visual cue"... The 1 2 3 sequence works because I have implemented it, even if the focus is lost during the process. Here is how it works: the selected text and the paragraph reference are stored (in the search box) so that it remains available when the focus changes (when the user types the name of the code/coding memo). 

At this stage, I have no idea how to implement such a visual cue, but be sure I will investigate. 

Again, many thanks for your feedback !

**Comment by christophe-lejeune** [comment]
Within the current (DOM) design, creating a persistent highlighting of the selected fragment (strictly speaking) would break lexical features. 

In the future, it is likely that this problem will disappear given that tagging and lexical features will belong to different pages. Indeed, when "tagging session" will be available, highlighting and coding will belong to the "tagging session" window. 

Meanwhile, a solution is to provide a visual cue for the paragraph that includes the selected fragment. The [just committed code](/Hypertopic/Cassandre/commit/4d0050537b567db85883b064179ec7f31cc9ece2) provides such a feature. When a fragment is selected, the background of the paragraph surrounding it becomes grey, and a `coding` icon suggests that it can be coded. This color and icon remain if the focus changes (when the user is writing the code name). This behavior is restricted to field & interview memos that can be coded.

Do not hesitate to comment this feature, to confirm whether the visual cue is sufficient and/or to propose improvements. 

Thank you very much for your collaboration !

**Comment by benel** [comment]
Weird. It worked. But I upgraded a few weeks ago and it doesn't work anymore. I will try to update to the latest version.

**Comment by christophe-lejeune** [comment]
Strange, indeed. 

As indicated above, this behavior is only provided for memos that can be coded. Two conditions should thus be met: 
* **Rights** You should be one of the contributors of the memo that you want to code.
* **Type** The memo that you want to code should be an interview transcript or a field memo.

Were these conditions met when you performed your last test?

**Comment by benel** [comment]
Yes, and I could create it. But there was no visual cue. 

My students currently transcribe their interview. So I cannot update my server yet. I will have to wait for early morning.

**Comment by benel** [comment]
I've updated Cassandre during the lunch break. Now it works. I was indeed at commit aba8ed2769666485c521daffacb2467c95a840e8 hence before 4d0050537b567db85883b064179ec7f31cc9ece2.
Sorry for the false report.
And thank you for the fix! 🥳
