### ISSUE TITLE
CouchDB unavailable after documents deletion

### ISSUE THREAD

**Issue by christophe-lejeune** [Hypertopic/Cassandre#16]
When multiple documents are deleted (even only 10 at once), CouchDB (version 1.0.1) enters views update. As a consequence, the whole base/application becomes unavailable for minutes (!). Such a behavior is not necessarily a bug, but the result is not really robust.

**Comment by benel** [comment]
> The idea is to have 2 different design documents:
> - one for heavy computation views (kwic, lexicometrics),
> - the other for simple views used to browse corpora.

I propose to refactor design documents as such:
- `app` for the Web user interface,
-  `api` for Hypertopic compliant services,
- `mining` for lexicometrics computing.

I'm still not sure about where to put the KWIC, since it must be accessible from both the app and the api. 

I will probably also move the rewrite logic to the proxy. 
Are you OK with this refactoring?

Do you have any ongoing non merged developments that you would want to finish before this big refactoring?

**Comment by christophe-lejeune** [comment]
Some days ago, I was precisely thinking about strategies to avoid the kind of downtime we are experiencing when documents are deleted or when some minor modification is made in the design document (almost any update causes such an inconvenience). I was about to propose a round robin balance between two CouchDB nodes in one cluster, which is (of course) costlier than the strategy you propose here. 

Have you conducted some tests that suggest that, when the indexer is busy on one design, other designs are still available ? 

I am currently abroad for holidays. I, however, have just merged last months developments. Albeit this was part of my purpose, I do not have enough time to further discuss this issue nor to publish a new release these days. 

Some developments were initiated before my departure, namely concerning a new graph rendering and the localization of sorting (because of diacritics). However, given these developments are at an early stage, a commit would be premature.

**Comment by christophe-lejeune** [comment]
Now that KWIC is moved into a separate design document, the situation should be improved. It however requires further tests to check whether the hereabove problem still occurs after documents deletion.
