### ISSUE TITLE
Get the Hypertopic item corresponding to a memo 

### ISSUE THREAD

**Issue by benel** [Hypertopic/Cassandre#84]
So that highlights made on Cassandre with LaSuli can be easily consulted in Porphyry,
Cassandre corpora and items identifiers should be kept in the other two software.

Hypertopic compliance seems to have been broken in Cassandre 3.

Intended behavior (on Cassandre 2):

```
GET http://cassandre.hypertopic.org/item/?resource=http://cassandre.hypertopic.org/text/enseignants-decrocheurs/deb51701fe5e555acf3a765a30115e04

{"rows":[
{"key":["http://cassandre.hypertopic.org/text/enseignants-decrocheurs/deb51701fe5e555acf3a765a30115e04"], "value":{"item":{"corpus":"enseignants-decrocheurs", "id":"deb51701fe5e555acf3a765a30115e04"}}}
]}
```

Broken behavior (on Cassandre 3):

```
GET http://www.cassandre-qda.ulg.ac.be/item/?resource=http://www.cassandre-qda.ulg.ac.be/memo/39567ff1a2780b51dab106835bc441b9/f9c2b8f91be5e587004d6f3c914ff0c9

{"rows":[
]}
```

**Comment by benel** [comment]
Would it be fixed by replacing `text` with `memo` on `https://github.com/Hypertopic/Cassandre/blob/master/lists/resource.js#L11`?

**Comment by christophe-lejeune** [comment]
Thank you for this feedback... and suggestion. Indeed, I have not been using this feature for a while. 

I will test this and keep you informed of the results.

**Comment by christophe-lejeune** [comment]
The proposed fix partially solves the issue. 

Indeed, replacing `text` with `memo` won't provide a different response because (currently) only transcripts are considered to be part of a corpus. In the above example, the requested URI concerns a storyline memo, which is thus not part of the corpus, strictly speaking, because it does not content piece of empirical material.  

Of course, the (currently implemented) definition of the corpus could be extended to any kinds of memo. This opens an interesting question. Do we consider the corpus is limited to speeches (ie transcripts), or does it include empirical materials (thus transcripts and field memos). Or do we consider any (interpretative) memo in a diary as an element of the corresponding corpus ? 

In the first and second alternatives, a corpus consists of empirical memos only. The desired response would be provided with a transcript, such as `http://www.cassandre-qda.ulg.ac.be/memo/ab11ce84866ed84ff6e8f23a9a002af2/ab11ce84866ed84ff6e8f23a9a01487c`

However, no resource is thus provided for a interpretive memo.  

```
GET http://www.cassandre-qda.ulg.ac.be/item/?resource=http://www.cassandre-qda.ulg.ac.be/memo/39567ff1a2780b51dab106835bc441b9/f9c2b8f91be5e587004d6f3c914ff0c9

{"rows":[
]}
```

In the third alternative, any kind of memos belongs to the corpus. The desired response would be provided for an interpretive memo.  

```
{"rows":[
{"key":["http://www.cassandre-qda.ulg.ac.be/memo/ab11ce84866ed84ff6e8f23a9a002af2/ab11ce84866ed84ff6e8f23a9a01487c"], "value":{"item":{"corpus":"ab11ce84866ed84ff6e8f23a9a002af2", "id":"ab11ce84866ed84ff6e8f23a9a01487c"}}}
]}
```

Alternatively, interpretive memo may be signaled as topic (I can imagine such a solution would not be ) or a "diary" key may be supplied in addition to the "corpus" one (but perhaps such a key would not match the Hypertopic protocol).

Illustration of the last alternative (for instance):

```
{"rows":[
{"key":["http://www.cassandre-qda.ulg.ac.be/memo/ab11ce84866ed84ff6e8f23a9a002af2/ab11ce84866ed84ff6e8f23a9a01487c"], "value":{"item":{"diary":"ab11ce84866ed84ff6e8f23a9a002af2", "id":"ab11ce84866ed84ff6e8f23a9a01487c"}}}
]}
```

We can of course "fix" the behavior prior to solve this complex question.

**Comment by benel** [comment]
I suppose answering this question is equivalent to this one: "Which memos should be highlightable?"

**Comment by christophe-lejeune** [comment]
Indeed. Arguments can be found for any option. 

A reasonable strategy would perhaps consist in allowing to highlight any kind of memo. This option is the most permissive. In such a case, the whole diary would be considered as a corpus (in the sense it is defined in the Hypertopic protocol).

Would you argue in this direction ?

**Comment by christophe-lejeune** [comment]
The fix thus requires little refactoring. In addition to the replacement you suggested, the [resource view](https://github.com/Hypertopic/Cassandre/blob/master/views/resource/map.js) would have to be modified as follows: 

```
-  if (o.corpus) {
-    emit(o._id, {corpus:o.corpus, item:o._id});
+  if (o.diary || o.corpus) {
+    var corpus = o.diary || o.corpus;
+    emit(o._id, {corpus:corpus, item:o._id});
```
This code is already in my working directory... Once fully tested, it will be part of my next commit (whose date is still unknown).
