### ISSUE TITLE
Problem displaying the diagram view

### ISSUE THREAD

**Issue by ValentinBerthou** [Hypertopic/Cassandre#95]
I have a problem with Cassandre : when I open my logbook, on the main page, when I want to change the data viewing mode and switch the display to see the network appear, the page reloads but shows the same thing...

How to work around or solve the problem?

**Comment by ValentinBerthou** [comment]
I have a problem with Cassandre : when I open my logbook, on the main page, when I want to change the data viewing mode and switch the display to see the network diagram appear, the page reloads but shows the same thing... 

How to work around or solve the problem?

**Comment by christophe-lejeune** [comment]
As the export features, the network and the timeline views  are currently refactored. That's why they disappeared from the diary page, on the production server.

Users report that they rarely use these features. That's why it is not a priority refactoring. However, these feature won't disappear forever. One day, they will be back.  

Do not hesitate to let me know which one of these features you are lacking. Such a feedback may instruct the refactoring.
