### ISSUE TITLE
Migrating interview transcripts from Cassandre 2 to Cassandre 3

### ISSUE THREAD

**Issue by benel** [Hypertopic/Cassandre#96]
To migrate interview transcripts from Cassandre 2 to Cassandre 3, I figured that, from CouchDB interface, I had to:
- create a corpus with a `diary_name` and the corpus ID referenced in transcripts,
- creating every transcript with a copy and paste
  - with `_rev` removed,
  - with  `"contributors": ["acme"], "readers": ["acme"]` added (where "acme" is the user who should 'own' it),
  - renaming the attribute I used for the creation date as `date` and reformatting the value as `year-month-date`.

However, I cannot figure out how to rename the attribute for the interviewer. I tried `creator`, `author`, `user`, `interviewer` but I still get `Créé par le 1er janvier 2012` (which means that the name is an empty string).

**Comment by christophe-lejeune** [comment]
Cassandre 3.0 was designed so that a CouchDB database populated with documents from a previous version may be used with no modification required. 

This implies that : 
* No memo type should be introduced. By default, Cassandre will assume that a document with no type is a transcript. 
* The field `contributors` and `readers` are not mandatory. The `user` field may be used to infer ownership (I am not totally sure).
* In such a context, the `_rev` field shouldn't be modified or removed. It will not affect anything. 
* The `speeches` will be integrated as the body of the memo. Cassandre will index these speeches (as is) for lexicometrics and KWIC's features.
* Attributes will remain untouched. 
* If a `date` is provided, it will be used as creation date. However, Cassandre won't consider a transcript has a creator if the document has no history (as you have experience, the creator is then an empty string). This implies that the first edition of the document (inside Cassandre 3) will be considered as a creation. This may be confusing at first glance... However, it you consider the history of the diary, this makes sense. 

I would be curious that you test these behaviors (as nobody as done yet up to now, as far as I know). 

However, if you dislike default behaviors, you can insert `contributors` and `readers` (exactly as you assume) and forge a minimal history with the creator as first user and the date when the document was created : `"history": [{"user": "acme",  "date": "2012-01-01"}]`

**Comment by benel** [comment]
I didn't updated Cassandre since most of documents where not used anymore. 
Therefore I installed another server with another version and just copied a few diaries.

**Comment by benel** [comment]
Here is an extract of the memo in JSON and its HTML display:

<img width="247" alt="Capture d’écran 2019-11-08 à 18 42 17" src="https://user-images.githubusercontent.com/597307/68498658-add43f80-0257-11ea-9696-b23722b78122.png">
<img width="526" alt="Capture d’écran 2019-11-08 à 18 40 13" src="https://user-images.githubusercontent.com/597307/68498663-b0cf3000-0257-11ea-99f0-039a00523da9.png">

As explained earlier, everything works fine except the display of the creator's name since I don't know how to rename `inteviewer`.

I can also share the memo with you if you want to test different JSON keys.

**Comment by benel** [comment]
It seems that I read your answer too fast. OK I will create a minimal history so that the real author  can be credited.

**Comment by benel** [comment]
It worked. Thanks, Christophe!
